export enum PropertyType {
  AMOUNT = 'am',
  ANCHOR = 'a',
  ANGLE = 'an',
  OPACITY = 'o',
  POSITION = 'p',
  POINTS = 'pt',
  ROTATION = 'r',
  ROTATION_X = 'rx',
  ROTATION_Y = 'ry',
  ROTATION_Z = 'rz',
  SCALE = 's',
  SKEW_AXIS = 'sa',
  SKEW = 'sk',
  SHAPE = 'sh',
  EXPANSION = 'x',
  FEATHER = 'f',
  SIZE = 'sz',
  ROUNDNESS = 'rd',
  MITER_LIMIT = 'ml',
  STROKE_WIDTH = 'sw',
  NUMBER = 'nu',
  COLOR = 'cl',
  ORIENTATION = 'or',
  GRADIENT = 'gr',
  EFFECT_VALUE = 'v',
  CENTER = 'cn',
}
