export enum PropertyType {
  ANCHOR = 'a',
  OPACITY = 'o',
  POSITION = 'p',
  ROTATION = 'r',
  SCALE = 's',
  SKEW_AXIS = 'sa',
  SKEW = 'sk',
  SHAPE = 'sh',
  EXPANSION = 'x',
  FEATHER = 'f',
  SIZE = 'sz',
  ROUNDNESS = 'rd',
  MITER_LIMIT = 'ml',
  STROKE_WIDTH = 'sw',
  NUMBER = 'nu',
  COLOR = 'cl',
}
